version: '2'

services:
## SETUP MAGENTO ##
    unit-test:
        build: docker/phpfpm
        restart: always
        container_name: marketplace_unit-test
        volumes:
            - ./src:/storage
        command: /bin/sh -c "php -d memory_limit=2G vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist"
        networks:
            - network-back